// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Piatnica.Dal;

namespace Piatnica.Dal.Migrations
{
    [DbContext(typeof(PiatnicaContext))]
    partial class PiatnicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Piatnica.Dal.Models.Delay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("OrderEntryId");

                    b.Property<DateTime>("date");

                    b.Property<int>("delayOrder");

                    b.HasKey("id");

                    b.HasIndex("OrderEntryId");

                    b.ToTable("DelaysContext");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.DistanceHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Eventid");

                    b.Property<DateTime>("date");

                    b.Property<double>("distance");

                    b.Property<int?>("orderid");

                    b.HasKey("id");

                    b.HasIndex("Eventid");

                    b.HasIndex("orderid");

                    b.ToTable("DistancesHistoryContext");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.Event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("EventsContext");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.EventHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Eventid");

                    b.Property<int?>("OrderEntryId");

                    b.Property<DateTime>("date");

                    b.HasKey("id");

                    b.HasIndex("Eventid");

                    b.HasIndex("OrderEntryId");

                    b.ToTable("EventsHistoriesContext");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.LocationHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("date");

                    b.Property<double>("latitudeL");

                    b.Property<double>("longitude");

                    b.Property<int?>("orderid");

                    b.HasKey("id");

                    b.HasIndex("orderid");

                    b.ToTable("LocationsHistoriesContext");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("number");

                    b.HasKey("id");

                    b.ToTable("OrdersContext");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.OrderEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cargo");

                    b.Property<string>("comments");

                    b.Property<DateTime>("date");

                    b.Property<DateTime>("fromTime");

                    b.Property<string>("location");

                    b.Property<string>("orderType");

                    b.Property<int?>("orderid");

                    b.Property<int>("status");

                    b.Property<DateTime>("toTime");

                    b.HasKey("Id");

                    b.HasIndex("orderid");

                    b.ToTable("OrdersEntriesContext");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.OrderState", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("date");

                    b.Property<int?>("orderid");

                    b.Property<string>("state");

                    b.HasKey("id");

                    b.HasIndex("orderid");

                    b.ToTable("OrdersStatesContext");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.Delay", b =>
                {
                    b.HasOne("Piatnica.Dal.Models.OrderEntry", "OrderEntry")
                        .WithMany("delays")
                        .HasForeignKey("OrderEntryId");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.DistanceHistory", b =>
                {
                    b.HasOne("Piatnica.Dal.Models.Event", "Event")
                        .WithMany("DistanceHistories")
                        .HasForeignKey("Eventid");

                    b.HasOne("Piatnica.Dal.Models.Order", "order")
                        .WithMany("distanceHistories")
                        .HasForeignKey("orderid");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.EventHistory", b =>
                {
                    b.HasOne("Piatnica.Dal.Models.Event", "Event")
                        .WithMany("EventHistories")
                        .HasForeignKey("Eventid");

                    b.HasOne("Piatnica.Dal.Models.OrderEntry", "OrderEntry")
                        .WithMany("eventHistories")
                        .HasForeignKey("OrderEntryId");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.LocationHistory", b =>
                {
                    b.HasOne("Piatnica.Dal.Models.Order", "order")
                        .WithMany("locationHistories")
                        .HasForeignKey("orderid");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.OrderEntry", b =>
                {
                    b.HasOne("Piatnica.Dal.Models.Order", "order")
                        .WithMany("orderEntries")
                        .HasForeignKey("orderid");
                });

            modelBuilder.Entity("Piatnica.Dal.Models.OrderState", b =>
                {
                    b.HasOne("Piatnica.Dal.Models.Order", "order")
                        .WithMany("orderState")
                        .HasForeignKey("orderid");
                });
#pragma warning restore 612, 618
        }
    }
}
