// <auto-generated />
using System;
using ITMCode.Piatnica.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITMCode.Piatnica.Api.Migrations
{
    [DbContext(typeof(PiatnicaContext))]
    [Migration("20190716112552_changed")]
    partial class changed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.Delay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("DelayOrder");

                    b.Property<int?>("OrderEntryId");

                    b.HasKey("Id");

                    b.HasIndex("OrderEntryId");

                    b.ToTable("DelaysContext");
                });

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.EventHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<float>("Distance");

                    b.Property<string>("Name");

                    b.Property<int?>("OrderEntryId");

                    b.HasKey("Id");

                    b.HasIndex("OrderEntryId");

                    b.ToTable("EventsHistoriesContext");
                });

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.LocationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<double>("LatitudeL");

                    b.Property<double>("Longitude");

                    b.Property<int?>("OrderId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("LocationsHistoriesContext");
                });

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Number");

                    b.HasKey("Id");

                    b.ToTable("OrdersContext");
                });

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.OrderEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cargo");

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("FromTime");

                    b.Property<string>("Location");

                    b.Property<int?>("OrderId");

                    b.Property<string>("OrderType");

                    b.Property<int>("Status");

                    b.Property<DateTime>("ToTime");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdersEntriesContext");
                });

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.OrderState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int?>("OrderId");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdersStatesContext");
                });

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.Delay", b =>
                {
                    b.HasOne("ITMCode.Piatnica.Dal.Models.OrderEntry", "OrderEntry")
                        .WithMany("Delays")
                        .HasForeignKey("OrderEntryId");
                });

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.EventHistory", b =>
                {
                    b.HasOne("ITMCode.Piatnica.Dal.Models.OrderEntry", "OrderEntry")
                        .WithMany("EventHistories")
                        .HasForeignKey("OrderEntryId");
                });

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.LocationHistory", b =>
                {
                    b.HasOne("ITMCode.Piatnica.Dal.Models.Order", "Order")
                        .WithMany("LocationHistories")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.OrderEntry", b =>
                {
                    b.HasOne("ITMCode.Piatnica.Dal.Models.Order", "Order")
                        .WithMany("OrderEntries")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ITMCode.Piatnica.Dal.Models.OrderState", b =>
                {
                    b.HasOne("ITMCode.Piatnica.Dal.Models.Order", "Order")
                        .WithMany("OrderState")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
